# Generated by Django 3.2.15 on 2022-09-07 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
