# Generated by Django 3.2.15 on 2022-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_suggestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='has_delete_action',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='has_rename_action',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
