# Generated by Django 3.2.16 on 2023-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_auto_20220912_1425"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("job_title", models.CharField(max_length=256, unique=True)),
                ("slug", models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ("skills", models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name="skillsentence",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="user",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="SkillSentence",
        ),
        migrations.DeleteModel(
            name="Suggestion",
        ),
    ]
