# Generated by Django 3.2.16 on 2023-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0007_alter_recommendation_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="bad_skills",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="good_skills",
            field=models.JSONField(default=list),
        ),
    ]
