# Generated by Django 3.2.16 on 2023-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20230115_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='source',
            field=models.CharField(choices=[('openai', 'openai'), ('taxonomy', 'taxonomy')], default='openai', max_length=32),
            preserve_default=False,
        ),
    ]
