# Generated by Django 3.2.16 on 2023-01-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_recommendation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='image_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
